export const COMPANIES = [
    { name: 'Google', slug: 'google', color: '#4285F4', icon: 'google' },
    { name: 'Amazon', slug: 'amazon', color: '#FF9900', icon: 'amazon' },
    { name: 'Apple', slug: 'apple', color: '#A2AAAD', icon: 'apple' },
    { name: 'Meta', slug: 'facebook', color: '#0668E1', icon: 'meta' },
    { name: 'Microsoft', slug: 'microsoft', color: '#00A4EF', icon: 'microsoft' },
    { name: 'Netflix', slug: 'netflix', color: '#E50914', icon: 'netflix' },
    { name: 'Uber', slug: 'uber', color: '#000000', icon: 'uber' },
    { name: 'Twitter', slug: 'twitter', color: '#1DA1F2', icon: 'twitter' },
    { name: 'Adobe', slug: 'adobe', color: '#FF0000', icon: 'adobe' },
    { name: 'Airbnb', slug: 'airbnb', color: '#FF5A5F', icon: 'airbnb' },
    { name: 'Salesforce', slug: 'salesforce', color: '#00A1E0', icon: 'salesforce' },
    { name: 'Oracle', slug: 'oracle', color: '#F80000', icon: 'oracle' },
    { name: 'Tesla', slug: 'tesla', color: '#CC0000', icon: 'tesla' },
    { name: 'Spotify', slug: 'spotify', color: '#1DB954', icon: 'spotify' },
    { name: 'LinkedIn', slug: 'linkedin', color: '#0A66C2', icon: 'linkedin' },
    { name: 'Snapchat', slug: 'snapchat', color: '#FFFC00', icon: 'snapchat' },
    { name: 'Palantir', slug: 'palantir', color: '#101113', icon: 'palantir' },
    { name: 'Coinbase', slug: 'coinbase', color: '#0052FF', icon: 'coinbase' },
    { name: 'Goldman Sachs', slug: 'goldmansachs', color: '#7399C6', icon: 'goldmansachs' },
    { name: 'JPMorgan', slug: 'jpmorgan', color: '#1B1464', icon: 'jpmorgan' },
];
