export const COMPANIES = [
    { name: 'Google', slug: 'google', color: '#4285F4', icon: 'google', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg' },
    { name: 'Amazon', slug: 'amazon', color: '#FF9900', icon: 'amazon', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg' },
    { name: 'Apple', slug: 'apple', color: '#A2AAAD', icon: 'apple', logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg' },
    { name: 'Meta', slug: 'facebook', color: '#0668E1', icon: 'meta', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Facebook_Logo_%282019%29.png' },
    { name: 'Microsoft', slug: 'microsoft', color: '#00A4EF', icon: 'microsoft', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg' },
    { name: 'Netflix', slug: 'netflix', color: '#E50914', icon: 'netflix', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg' },
    { name: 'Uber', slug: 'uber', color: '#000000', icon: 'uber', logo: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png' },
    { name: 'Twitter', slug: 'twitter', color: '#1DA1F2', icon: 'twitter', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Logo_of_Twitter.svg' },
    { name: 'Adobe', slug: 'adobe', color: '#FF0000', icon: 'adobe', logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Adobe_Systems_logo_and_wordmark.svg' },
    { name: 'Airbnb', slug: 'airbnb', color: '#FF5A5F', icon: 'airbnb', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg' },
    { name: 'Salesforce', slug: 'salesforce', color: '#00A1E0', icon: 'salesforce', logo: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Salesforce.com_logo.svg' },
    { name: 'Oracle', slug: 'oracle', color: '#F80000', icon: 'oracle', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/50/Oracle_logo.svg' },
    { name: 'Tesla', slug: 'tesla', color: '#CC0000', icon: 'tesla', logo: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Tesla_Motors.svg' },
    { name: 'Spotify', slug: 'spotify', color: '#1DB954', icon: 'spotify', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg' },
    { name: 'LinkedIn', slug: 'linkedin', color: '#0A66C2', icon: 'linkedin', logo: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png' },
    { name: 'Snapchat', slug: 'snapchat', color: '#FFFC00', icon: 'snapchat', logo: 'https://upload.wikimedia.org/wikipedia/en/c/c4/Snapchat_logo.svg' },
    { name: 'Palantir', slug: 'palantir', color: '#101113', icon: 'palantir', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Palantir_Technologies_logo.svg' },
    { name: 'Coinbase', slug: 'coinbase', color: '#0052FF', icon: 'coinbase', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Coinbase.svg' },
    { name: 'Goldman Sachs', slug: 'goldmansachs', color: '#7399C6', icon: 'goldmansachs', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/61/Goldman_Sachs.svg' },
    { name: 'JPMorgan', slug: 'jpmorgan', color: '#1B1464', icon: 'jpmorgan', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/JPMorgan_Chase_Logo_2008_1.svg' },
];
