import React from 'react';
import { motion } from 'framer-motion';
import { FileText, Lock } from 'lucide-react';
import { Link } from 'react-router-dom';
import './TermsAndConditions.css';
import { useSEO } from './hooks/useSEO';

export default function TermsAndConditions() {
    useSEO({
        title: 'Terms & Conditions – Whizan AI',
        description: 'Terms and conditions for using Whizan AI.',
        canonical: '/terms'
    });

    return (
        <div className="tc-page">
            <div className="tc-container">
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="tc-header"
                >
                    <div className="tc-icon-wrap">
                        <FileText size={32} />
                    </div>
                    <h1>Terms and Conditions</h1>
                    <p>Last updated: March 21, 2026</p>
                </motion.div>

                <motion.div 
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.1 }}
                    className="tc-content"
                >
                    <section className="tc-section">
                        <h2>1. Acceptance of Terms</h2>
                        <p>
                            By creating an account, accessing, or using Whizan AI ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you may not access the Service.
                        </p>
                    </section>

                    <section className="tc-section">
                        <h2>2. Description of Service</h2>
                        <p>
                            Whizan AI provides an AI-powered interview preparation platform, including but not limited to Data Structures and Algorithms (DSA) practice, AI mock interviews, System Design evaluations, and portfolio generation tools. The features and capabilities of the Service may be updated or modified from time to time without prior notice.
                        </p>
                    </section>

                    <section className="tc-section">
                        <h2>3. User Accounts</h2>
                        <p>
                            To utilize certain functionalities of Whizan AI, you are required to create an account. You agree to:
                        </p>
                        <ul>
                            <li>Provide accurate, current, and complete information during registration.</li>
                            <li>Maintain the security of your password and credentials.</li>
                            <li>Take full responsibility for all activities that occur under your account.</li>
                        </ul>
                    </section>

                    <section className="tc-section">
                        <h2>4. Acceptable Use</h2>
                        <p>
                            You agree not to misuse the Service or help anyone else do so. Specifically, you agree not to:
                        </p>
                        <ul>
                            <li>Attempt to copy, modify, duplicate, or reverse engineer any part of the Service.</li>
                            <li>Use the Service for any illegal or unauthorized purpose.</li>
                            <li>Interfere with or disrupt the integrity or performance of the Service.</li>
                            <li>Harvest or collect data using automated scraping tools, unless explicitly allowed by the platform.</li>
                        </ul>
                    </section>

                    <section className="tc-section">
                        <h2>5. AI Interactions and Feedback</h2>
                        <p>
                            The mock interviews, evaluations, code testing, and feedback generated by Whizan AI are provided by artificial intelligence. While we strive for accuracy, the Service is for educational purposes only. We do not guarantee employment, academic success, or the complete accuracy of AI-generated advice.
                        </p>
                    </section>

                    <section className="tc-section">
                        <h2>6. Privacy and Data Security</h2>
                        <div className="tc-icon-text">
                            <Lock size={18} />
                            <span>Your data is protected and handled according to our standard security protocols. We do not sell your personal coding data to third parties.</span>
                        </div>
                        <p>
                            By using the platform, you allow us to store and process your submissions, interview recordings, and profile data to improve our machine learning models and enhance user experience. 
                        </p>
                    </section>

                    <section className="tc-section">
                        <h2>7. Modifications to Terms</h2>
                        <p>
                            We reserve the right to modify or replace these Terms at any time. We will provide reasonable notice of any significant changes. Your continued use of the Service following the posting of any changes constitutes acceptance of those changes.
                        </p>
                    </section>
                </motion.div>

                <motion.div 
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.2 }}
                    className="tc-footer"
                >
                    <Link to="/" className="tc-back-btn">
                        Return to Home
                    </Link>
                </motion.div>
            </div>
        </div>
    );
}
